# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tinkersaleProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
  # Pods for tinkersaleProject

  target 'tinkersaleProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing


  end

  target 'tinkersaleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tinkersaleProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tinkersaleProject-tvOS

  target 'tinkersaleProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
